### ISSUE TITLE
Use with packages

### ISSUE THREAD

**Issue by thetechnaddict** [monbro/meteor-breadcrumb-plugin#9]
When I am working with a package that has routes defined, without having provided a parent and tile parameters, is there any way I can add them in the app? (without cloning them into a local package that is)

**Comment by monbro** [comment]
I am not sure if I understand your question correctly. Do you want to ignore the routes without any parent and title attribute?

**Comment by thetechnaddict** [comment]
mm... poorly phrased question from me...

Perhaps better to ask - 'how or can we use the breadcrumb plugin when using packages that have routes  within the package.

For instance xolvio:md-blog has routes defined - one for the blog list, one for the blog post and so on...

When setting up the blog we define a layout that could include a breadcrumb - but how would we use these two packages together?

**Comment by monbro** [comment]
You need to override the route options for the package md-blog somehow. As I see they are inside: https://github.com/xolvio/md-blog/blob/master/src/client/blog-route.js

The easiest might be to clone the package into the package folder of our own application and to add the breadcrumb package into the md-blog package. To do so you can add the following into the package.js file:

```
Package.onUse(function(api) {
    api.use('momentjs:moment');
});
```

Check if you need to add the package (in this example momentjs) to the app itself as well, I am not sure currently.

Otherwise then that, there is nothing I can do according to the breadcrumb plugin to fix your problem.

**Comment by thetechnaddict** [comment]
Thank you - clone it is..
